### ISSUE TITLE
VirtualPlayers2 not copying WorldEdit selection to be saved as schematic

### ISSUE THREAD

**Issue by Vampsku11** [BattlePlugins/VirtualPlayers#1]
Using Paper 1.9.2, WorldEdit 7.0.1 and VirtualPlayers2 1.8.3 and no other plugins

Commands are not giving errors, and schematic file is being generated. However the schematic is empty. If I load and paste the schematic nothing will appear.

> dc temp tp world,206,5,-121
> dc temp /pos1 203,5,-121
> dc temp /pos2 205,5,-121
> dc temp /copy
> dc temp schematic save badlands1
[17:43:51 INFO]: [temp] 'temp teleporting from 0.0,0.0,0.0 -> 206.0,5.0,-121.0'
[17:43:51 INFO]:  temp executing '/pos1 203,5,-121'
[17:43:51 INFO]: [temp] 'temp gettingMessage= First position set to (203, 5, -121).'
[17:43:51 INFO]:  temp executing '/pos2 205,5,-121'
[17:43:51 INFO]: [temp] 'temp gettingMessage= Second position set to (205, 5, -121) (3).'
[17:43:51 INFO]:  temp executing '/copy'
[17:43:51 INFO]: [temp] 'temp gettingMessage= 3 block(s) affected.'
[17:43:51 INFO]:  temp executing 'schematic save badlands1'
[17:43:51 INFO]: temp saved /mc-server/plugins/WorldEdit/schematics/badlands1.schem

**Comment by Redned235** [comment]
Yes, this is a known issue. You have to use a custom version of WorldEdit found [here](http://rainbowcraft.sytes.net/download/plugins/WorldEdit/v6.1.1-SNAPSHOT/). Unfortunately this is an issue due to how WorldEdit is coded and there isn't much we can do about it. The only way around it is by using this custom version.

Apologies for the inconvenience.

**Comment by Redned235** [comment]
I also noticed you said you were on Paper 1.9.2 using WorldEdit 7.0.1. I would like to point out that WorldEdit 7.0.1 only works on 1.13 and 1.14 right now; so as a whole WorldEdit shouldn't even be working.

**Comment by Vampsku11** [comment]
Paper build 1.9.2 for 1.14.4 specifically

Thank you. The bukkit page suggested that version 7 should not have the issue. It looks like version 6 may be for an older version of Minecraft.

**Comment by Redned235** [comment]
> Paper build 1.9.2 for 1.14.4 specifically
> 
> Thank you. The bukkit page suggested that version 7 should not have the issue. I will try verion 6.

Ah alright. Version 6 doesn't work on 1.14 as far as I know. The WorldEdit developers fixed this issue in version 7 supposedly and stated so in their changelog. I'll do some testing of my own later tonight.

Thank you for the report.

**Comment by Vampsku11** [comment]
A couple of days ago the WorldEdit devs released a snapshot that allows some commands to be used from the server console, and after chatting with them they were able to resolve an issue that allows me to use the commands above.

**Comment by Redned235** [comment]
> A couple of days ago the WorldEdit devs released a snapshot that allows some commands to be used from the server console, and after chatting with them they were able to resolve an issue that allows me to use the commands above.

What was the issue?

**Comment by Vampsku11** [comment]
Sorry, I just came back to clarify the commands were run directly from WorldEdit and not from a virtual player.

**Comment by Redned235** [comment]
> Sorry, I just came back to clarify the commands were run directly from WorldEdit and not from a virtual player.

Alright, thank you for the clarification.
